### ISSUE TITLE
Trying to get in contact with thomasnordquist

### ISSUE THREAD

**Issue by bj00rn** [snordquist/dyndns_route53_lambda#1]
Hi, 

Sorry for busting in like this. I (and a lot of others) are trying to get the attention from thomasnordquist on the status of MQTT-Explorer project. It's such a great project but regretfully it seems that it has been abandoned.

I saw that you are following each other. 

If you are in contact with him would you please relay to him to have a look at and give us his thoughts

https://github.com/thomasnordquist/MQTT-Explorer/issues/730#issuecomment-1695449495

Cheers!

**Comment by ilgrank** [comment]
Hi, and Sorry for bothering too. Just hoping too you can get in contact with @thomasnordquist 
Thanks!

**Comment by Jackfritt** [comment]
I think his family took it over to this one...
https://mqtt-explorer.com/
https://github.com/thomasnordquist/MQTT-Explorer

**Comment by bj00rn** [comment]
> I think his family took it over to this one... https://mqtt-explorer.com/ https://github.com/thomasnordquist/MQTT-Explorer

What do you mean?

**Comment by snordquist** [comment]
He is aware but might currently not have any interest in maintaining or extending this project. You can try to make him an offer.

**Comment by bj00rn** [comment]
@snordquist Thanks for reply! There are many of us in the open source community willing to step in and move the project forward! The only thing keeping us back is the license model which currently does not allow the project to be forked (no derivatives).

If you could relay a message to him and ask if he would consider changing the license to allow derivatives I would be grateful!

Again thanks for you reply, I will not bother you anymore.
